- job:
    name: keystone-protection-functional
    parent: keystone-dsvm-py3-functional
    voting: false
    vars:
      tempest_test_regex: 'keystone_tempest_plugin.tests.rbac'
      devstack_localrc:
        KEYSTONE_ENFORCE_SCOPE: True
      devstack_plugins:
        keystone: https://opendev.org/openstack/keystone
      devstack_services:
        g-api: false
        n-api: false
        n-api-meta: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-sch: false
        placement-api: false
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
      devstack_local_conf:
        post-config: {}

- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - keystone-dsvm-py3-functional
        - keystone-dsvm-py3-functional-federation-ubuntu-jammy:
            voting: false
        - keystone-dsvm-py3-functional-federation-ubuntu-jammy-k2k
        - keystone-dsvm-py3-functional-2024-2
        - keystone-dsvm-py3-functional-2024-1
        - keystone-dsvm-py3-functional-2023-2
        - keystone-protection-functional
    gate:
      jobs:
        - keystone-dsvm-py3-functional
        - keystone-dsvm-py3-functional-federation-ubuntu-jammy-k2k
        - keystone-protection-functional

- job:
    name: keystone-dsvm-py3-functional-2024-2
    parent: keystone-dsvm-py3-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2

- job:
    name: keystone-dsvm-py3-functional-2024-1
    parent: keystone-dsvm-py3-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1

- job:
    name: keystone-dsvm-py3-functional-2023-2
    parent: keystone-dsvm-py3-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.2
